/**
 * GENERATED by scripts/codemod-copy.ts site — do not edit.
 *
 * The id prefixes of every client component in the site scope. The root
 * layout provides these rows through <CopyScope>, so the platform's client
 * components (nested many levels deep, rendered on every product page) read
 * their copy without a scope each. Re-run the codemod after adding one.
 */
export const SITE_CLIENT_COPY_PREFIXES: string[] = [
  "site.getstarted.checkoutbutton.",
  "site.platform.deploylight.",
  "site.platform.design.designmode.",
  "site.platform.membersgrid.",
  "site.platform.producttopnav.",
  "site.platform.profilemenu.",
  "site.platform.research.evolvement.",
  "site.platform.research.researchnav.",
  "site.platform.research.researchsearch.",
  "site.platform.research.sectiondive.",
  "site.platform.research.share.sharecard.",
  "site.platform.research.share.sharegenerate.",
  "site.platform.research.topologygraph.",
  "site.platform.reviewqueue.",
  "site.platform.roadmapwish.",
  "site.platform.settings.compspanel.",
  "site.platform.settings.productadminwidgets.",
  "site.platform.sitedock.",
  "site.platform.slides.slidesviewer.",
  "site.platform.viberbar.",
  "site.platform.voiceinputbutton.",
  "site.platform.wishboard.",
  "site.platform.wishtimeline.",
  "site.settings.billing.controls.",
  "site.setup.setupactions.",
  "site.setup.setupforms.",
  "site.signin.signinform."
];
