/**
 * Embed the Inference Economics game as strings, and write its schema as SQL.
 *
 *   pnpm game:embed
 *
 * Reads  app/(products)/inference-economics/_game/index.html
 *        app/(products)/inference-economics/_game/game.js
 * Writes app/(products)/inference-economics/_game/bundle.ts   (the strings the routes serve)
 *        app/(products)/inference-economics/data/schema.sql   (the declaration, as SQL)
 *
 * The route handlers serve from the generated module rather than reading the
 * files at request time, so the deployment needs no file-system tracing. The
 * .html and .js remain the source a person edits; run this after editing.
 * `pnpm test` fails if the generated files are stale.
 */
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";

import { SCHEMA_SQL } from "../app/(products)/inference-economics/data/schema";

const DIR = path.join(process.cwd(), "app/(products)/inference-economics");
const html = fs.readFileSync(path.join(DIR, "_game/index.html"), "utf8");
const js = fs.readFileSync(path.join(DIR, "_game/game.js"), "utf8");
const hash = createHash("sha256").update(js).digest("hex").slice(0, 16);

const bundle = `/* GENERATED by scripts/embed-game.ts from _game/index.html and _game/game.js — do not edit. */
export const GAME_JS_HASH = ${JSON.stringify(hash)};
export const GAME_HTML: string = ${JSON.stringify(html)};
export const GAME_JS: string = ${JSON.stringify(js)};
`;

const write = (rel: string, text: string) => {
  const p = path.join(DIR, rel);
  const before = fs.existsSync(p) ? fs.readFileSync(p, "utf8") : null;
  if (before === text) { console.log(`  ${rel}: unchanged`); return; }
  fs.writeFileSync(p, text);
  console.log(`  ${rel}: written (${(text.length / 1024).toFixed(0)} KB)`);
};

write("_game/bundle.ts", bundle);
write("data/schema.sql", SCHEMA_SQL);
